Title: "EDM Portfolio"
Description: "Enterprise Data Management Portfolio"
Logo: ![image alt](https://github.com/natdungca23/EDM-PORTFOLIO/blob/e4368e1ec66f2ae269a7cfaf7088eefcc1f47536/Midterm-Task%201/Screenshot%202025-03-03%20131906.png)
#show_downloads: true
theme: jekyll-theme-minimal 


